**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [ ]:
import numpy as np

arr_1 = np.array([5, 15, 25, 35, 45])
zeros_arr = np.zeros(7)
ones_arr = np.ones(6)
arr_2 = np.arange(10, 20)

print(arr_1)
print(zeros_arr)
print(ones_arr)
print(arr_2)


[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [3]:
initial_arr = np.arange(12, 61, 12)

mult_by_two_arr = initial_arr * 2
add_ten_arr = initial_arr + 10
squared_arr = initial_arr ** 2
root_squared_arr = np.sqrt(initial_arr)

print(initial_arr)
print(mult_by_two_arr)
print(add_ten_arr)
print(squared_arr)
print(root_squared_arr)

[12 24 36 48 60]
[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [4]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

print('mean:', np.mean(data))
print('min:', np.min(data))
print('max:', np.max(data))
print('mean:', np.sum(data))

mean: 45.42857142857143
min: 18
max: 79
mean: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [5]:
arr = np.array([15, 22, 35, 44, 58, 67])

print('first:', arr[0])
print('last:', arr[-1])
print('from 1 to 3 index:', arr[1:4])
print('greater than 40:', arr[arr > 40])

first: 15
last: 67
from 1 to 3 index: [22 35 44]
greater than 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [6]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [7]:
print('shape:', matrix.shape)
print('first row:', matrix[0, :])
print('second col:', matrix[:, 1])
print('sum:', np.sum(matrix))
print('mean:', np.mean(matrix))

shape: (3, 3)
first row: [2 4 6]
second col: [ 4 10 16]
sum: 90
mean: 10.0


In [20]:
size = 1_000_000
run_count = 1000
python_list = list(range(size))
numpy_array = np.arange(size)


In [26]:
import time

start = time.time()

times_arr = []

for _ in range(run_count):
    result = [x * 2 for x in python_list]
    now = time.time()
    times_arr.append(now - start)
    start = now

print(f"Python цикл: {sum(times_arr) / len(times_arr)} сек")

Python цикл: 0.01343664312362671 сек


In [27]:
start = time.time()

times_arr = []

for _ in range(run_count):
    result = numpy_array * 2
    now = time.time()
    times_arr.append(now - start)
    start = now

print(f"NumPy: {np.mean(times_arr)} сек")

NumPy: 0.0006112809181213379 сек


In [28]:
0.01343664312362671 / 0.0006112809181213379

21.981126394263732